import { CITIES } from "./cities";
import { PROVINCES } from "./provinces";

const BSS_FLOW = {
  title: "open_nex_account",
  pages: [
    {
      pageType: "normal",
      sections: [
        {
          title: "personal_info",
          subtitle: "enter_your_info",
          fields: [
            {
              id: "full_name",
              title: "legal_name",
              inputType: "text",
            },
            {
              id: "ktp_number",
              title: "ktp_number",
              inputType: "text",
            },
            {
              id: "gender",
              title: "gender",
              inputType: "radioButtonH",
              values: [
                { id: "female", text: "female" },
                { id: "male", text: "male" },
              ],
            },
            {
              id: "date_of_birth",
              title: "date_of_birth",
              inputType: "textDate",
            },
            {
              id: "place_of_birth",
              title: "place_of_birth",
              inputType: "text",
            },
            {
              id: "marital_status",
              title: "marital_status",
              inputType: "radioButtonH",
              values: [
                { id: "single", text: "single" },
                { id: "married", text: "married" },
              ],
            },
            {
              id: "mother_name",
              title: "mother_maiden_name",
              inputType: "text",
            },
          ],
        },
        {
          title: "hidden",
          subtitle: "hidden",
          isHidden: true,
          fields: [
            {
              id: "ktp_rtwt",
              title: "ktp_rtwt",
              inputType: "text",
            },
          ],
        },
      ],
    },
    {
      pageType: "normal",
      sections: [
        {
          title: "address_in_ktp",
          subtitle: "confirm_ktp_address",
          fields: [
            {
              id: "ktp_address",
              title: "full_address",
              inputType: "multiLineText",
            },
            {
              id: "ktp_province",
              title: "province",
              inputType: "searchList",
              sharedValuesId: "provinces",
            },
            {
              id: "ktp_city",
              title: "city",
              inputType: "searchList",
              sharedValuesId: "cities",
            },
            {
              id: "ktp_district",
              title: "district",
              inputType: "text",
            },
            {
              id: "ktp_subdistrict",
              title: "subdistrict",
              inputType: "text",
            },
            {
              id: "ktp_postal_code",
              title: "postal_code",
              inputType: "text",
            },
          ],
        },
        {
          title: "mailing_address",
          enableSwitch: {
            text: "mailing_same_as_ktp",
            defaultValue: true,
            showWhenTicked: false,
            copyBehavior: "whenContinued",
          },
          fields: [
            {
              id: "mailing_address",
              title: "full_address",
              inputType: "multiLineText",
              copyId: "ktp_address",
            },
            {
              id: "mailing_province",
              title: "province",
              inputType: "searchList",
              sharedValuesId: "provinces",
              copyId: "ktp_province",
            },
            {
              id: "mailing_city",
              title: "city",
              inputType: "searchList",
              sharedValuesId: "cities",
              copyId: "ktp_city",
            },
            {
              id: "mailing_district",
              title: "district",
              inputType: "text",
              copyId: "ktp_district",
            },
            {
              id: "mailing_subdistrict",
              title: "subdistrict",
              inputType: "text",
              copyId: "ktp_subdistrict",
            },
            {
              id: "mailing_postal_code",
              title: "postal_code",
              inputType: "text",
              copyId: "ktp_postal_code",
            },
          ],
        },
      ],
    },
    {
      pageType: "normal",
      sections: [
        {
          title: "email_address",
          subtitle: "provide_active_email",
          fields: [
            {
              id: "email_address",
              title: "email_address",
              inputType: "text",
            },
          ],
        },
      ],
    },
    {
      pageType: "normal",
      sections: [
        {
          title: "employment_details",
          subtitle: "enter_employment_details",
          fields: [
            {
              id: "job_title",
              title: "job_title",
              inputType: "searchList",
              values: [
                { id: "001", text: "job_001" },
                { id: "002", text: "job_002" },
                { id: "003", text: "job_003" },
                { id: "004", text: "job_004" },
                { id: "005", text: "job_005" },
                { id: "006", text: "job_006" },
                { id: "007", text: "job_007" },
                { id: "008", text: "job_008" },
                { id: "009", text: "job_009" },
                { id: "010", text: "job_010" },
                { id: "011", text: "job_011" },
                { id: "012", text: "job_012" },
                { id: "013", text: "job_013" },
                { id: "014", text: "job_014" },
                { id: "015", text: "job_015" },
                { id: "016", text: "job_016" },
                { id: "017", text: "job_017" },
                { id: "018", text: "job_018" },
                { id: "019", text: "job_019" },
                { id: "020", text: "job_020" },
                { id: "021", text: "job_021" },
                { id: "022", text: "job_022" },
                { id: "023", text: "job_023" },
                { id: "024", text: "job_024" },
                { id: "025", text: "job_025" },
                { id: "026", text: "job_026" },
                { id: "027", text: "job_027" },
                { id: "028", text: "job_028" },
                { id: "029", text: "job_029" },
                { id: "030", text: "job_030" },
                { id: "031", text: "job_031" },
                { id: "032", text: "job_032" },
                { id: "033", text: "job_033" },
                { id: "034", text: "job_034" },
                { id: "035", text: "job_035" },
                { id: "036", text: "job_036" },
                { id: "099", text: "job_099" },
              ],
            },
            {
              id: "occupation",
              title: "occupation",
              inputType: "searchList",
              values: [
                { id: "1", text: "occupation_1" },
                { id: "2", text: "occupation_2" },
                { id: "3", text: "occupation_3" },
                { id: "4", text: "occupation_4" },
                { id: "5", text: "occupation_5" },
                { id: "6", text: "occupation_6" },
                { id: "7", text: "occupation_7" },
                { id: "8", text: "occupation_8" },
                { id: "9", text: "occupation_9" },
                { id: "10", text: "occupation_10" },
                { id: "30", text: "occupation_30" },
                { id: "33", text: "occupation_33" },
                { id: "38", text: "occupation_38" },
                { id: "40", text: "occupation_40" },
                { id: "55", text: "occupation_55" },
                { id: "58", text: "occupation_58" },
                { id: "68", text: "occupation_68" },
                { id: "74", text: "occupation_74" },
                { id: "76", text: "occupation_76" },
                { id: "80", text: "occupation_80" },
                { id: "81", text: "occupation_81" },
              ],
            },
            {
              id: "company_name",
              title: "company_name",
              inputType: "text",
            },
            {
              id: "nature_of_business",
              title: "nature_of_business",
              inputType: "searchList",
              values: [
                { id: "1000", text: "business_1000" },
                { id: "1100", text: "business_1100" },
                { id: "1200", text: "business_1200" },
                { id: "1600", text: "business_1600" },
                { id: "1700", text: "business_1700" },
                { id: "1800", text: "business_1800" },
                { id: "1900", text: "business_1900" },
                { id: "1910", text: "business_1910" },
                { id: "1920", text: "business_1920" },
                { id: "1930", text: "business_1930" },
                { id: "1940", text: "business_1940" },
                { id: "1950", text: "business_1950" },
                { id: "2000", text: "business_2000" },
                { id: "2100", text: "business_2100" },
                { id: "2200", text: "business_2200" },
                { id: "2300", text: "business_2300" },
                { id: "2310", text: "business_2310" },
                { id: "2320", text: "business_2320" },
                { id: "2330", text: "business_2330" },
                { id: "2400", text: "business_2400" },
                { id: "2410", text: "business_2410" },
                { id: "2420", text: "business_2420" },
                { id: "2440", text: "business_2440" },
                { id: "2460", text: "business_2460" },
                { id: "2470", text: "business_2470" },
                { id: "2480", text: "business_2480" },
                { id: "2490", text: "business_2490" },
                { id: "2500", text: "business_2500" },
                { id: "2510", text: "business_2510" },
                { id: "2520", text: "business_2520" },
                { id: "2530", text: "business_2530" },
                { id: "2540", text: "business_2540" },
                { id: "2550", text: "business_2550" },
                { id: "2600", text: "business_2600" },
                { id: "2610", text: "business_2610" },
                { id: "2620", text: "business_2620" },
                { id: "2630", text: "business_2630" },
                { id: "2700", text: "business_2700" },
                { id: "2800", text: "business_2800" },
                { id: "2810", text: "business_2810" },
                { id: "2820", text: "business_2820" },
                { id: "2830", text: "business_2830" },
                { id: "2840", text: "business_2840" },
                { id: "2850", text: "business_2850" },
                { id: "2900", text: "business_2900" },
                { id: "2910", text: "business_2910" },
                { id: "3000", text: "business_3000" },
                { id: "3100", text: "business_3100" },
                { id: "3110", text: "business_3110" },
                { id: "3120", text: "business_3120" },
                { id: "3130", text: "business_3130" },
                { id: "3140", text: "business_3140" },
                { id: "3200", text: "business_3200" },
                { id: "3300", text: "business_3300" },
                { id: "3400", text: "business_3400" },
                { id: "3900", text: "business_3900" },
                { id: "4000", text: "business_4000" },
                { id: "4100", text: "business_4100" },
                { id: "4110", text: "business_4110" },
                { id: "4120", text: "business_4120" },
                { id: "4200", text: "business_4200" },
                { id: "4210", text: "business_4210" },
                { id: "4220", text: "business_4220" },
                { id: "4310", text: "business_4310" },
                { id: "4320", text: "business_4320" },
                { id: "5000", text: "business_5000" },
                { id: "6000", text: "business_6000" },
                { id: "7000", text: "business_7000" },
                { id: "8000", text: "business_8000" },
                { id: "8190", text: "business_8190" },
                { id: "8200", text: "business_8200" },
                { id: "9000", text: "business_9000" },
              ],
            },
            {
              id: "monthly_income",
              title: "monthly_income",
              inputType: "list",
              values: [
                { id: "0", text: "amount_0_to_25" },
                { id: "25000000", text: "amount_25_to_50" },
                { id: "50000000", text: "amount_50_to_100" },
                { id: "100000000", text: "amount_100_to_500" },
                { id: "500000000", text: "amount_500_to_1k" },
                { id: "1000000000", text: "amount_gteq_1k" },
              ],
            },
            {
              id: "source_of_income",
              title: "source_of_income",
              inputType: "checkbox",
              values: [
                { id: "SALARY", text: "income_source_salary" },
                { id: "COMMISSION", text: "income_source_commission" },
                { id: "BUSINESS", text: "income_source_commission" },
                { id: "INVESTMENTS", text: "income_source_investments" },
                { id: "SALES_PROCEEDS", text: "income_source_sales_proceeds" },
                { id: "PENSION", text: "income_source_pension" },
                { id: "ALLOWANCE", text: "income_source_allowance" },
                { id: "INHERITANCE", text: "income_source_inheritance" },
                {
                  id: "OTHER",
                  text: "income_source_other",
                  extra: "please_specify",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      pageType: "normal",
      sections: [
        {
          title: "purpose_of_account",
          subtitle: "help_us_understand_account_purpose",
          fields: [
            {
              id: "purpose_of_account",
              title: "purpose_of_account",
              inputType: "list",
              values: [
                { id: "SAVINGS", text: "purpose_savings" },
                { id: "WORKING_CAPITAL", text: "purpose_working_capital" },
                { id: "INVESTMENT", text: "purpose_investment" },
                { id: "BUSINESS", text: "purpose_business" },
                { id: "COMMERCE", text: "purpose_commerce" },
              ],
            },
            {
              id: "monthly_withdrawal",
              title: "estimated_monthly_withdrawal",
              inputType: "list",
              values: [
                { id: "0", text: "amount_0_to_25" },
                { id: "25000000", text: "amount_25_to_50" },
                { id: "50000000", text: "amount_50_to_100" },
                { id: "100000000", text: "amount_100_to_500" },
                { id: "500000000", text: "amount_500_to_1k" },
                { id: "1000000000", text: "amount_gteq_1k" },
              ],
            },
          ],
        },
      ],
    },
  ],
  sharedValues: {
    cities: CITIES,
    provinces: PROVINCES,
  },
};
