export const PROVINCES = [
  { id: "1", text: "JAWA BARAT" },
  { id: "2", text: "BANTEN" },
  { id: "3", text: "DKI JAKARTA" },
  { id: "4", text: "D.I JOGJAKARTA" },
  { id: "5", text: "JAWA TENGAH" },
  { id: "6", text: "JAWA TIMUR" },
  { id: "7", text: "BENGKULU" },
  { id: "8", text: "JAMBI" },
  { id: "9", text: "NANGGROE ACEH DARUSSALAM" },
  { id: "10", text: "SUMATERA UTARA" },
  { id: "11", text: "SUMATERA BARAT" },
  { id: "12", text: "RIAU" },
  { id: "13", text: "SUMATERA SELATAN" },
  { id: "14", text: "KEPULAUAN BANGKA BELITUNG" },
  { id: "15", text: "LAMPUNG" },
  { id: "16", text: "KALIMANTAN SELATAN" },
  { id: "17", text: "KALIMANTAN BARAT" },
  { id: "18", text: "KALIMANTAN TIMUR" },
  { id: "19", text: "KALIMANTAN TENGAH" },
  { id: "20", text: "SULAWESI TENGAH" },
  { id: "21", text: "SULAWESI SELATAN" },
  { id: "22", text: "SULAWESI UTARA" },
  { id: "23", text: "GORONTALO" },
  { id: "24", text: "SULAWESI TENGGARA" },
  { id: "25", text: "NUSA TENGGARA BARAT" },
  { id: "26", text: "BALI" },
  { id: "27", text: "NUSA TENGGARA TIMUR" },
  { id: "28", text: "MALUKU" },
  { id: "29", text: "PAPUA TENGAH" },
  { id: "30", text: "MALUKU UTARA" },
  { id: "31", text: "KEPULAUAN RIAU" },
  { id: "32", text: "SULAWESI BARAT" },
  { id: "33", text: "PAPUA BARAT" },
  { id: "34", text: "PAPUA TIMUR" },
  { id: "35", text: "KALIMANTAN UTARA" },
];
